version: '3'
services:
  crawler:
    build: .
    links:
     - "selenium:selenium"
    volumes:
     - .:/workdir/output
  selenium:
    image: "selenium/standalone-chrome-debug"
  vnc-client:
    build:
      context: ./
      dockerfile: vnc-client.Dockerfile
    ports:
     - "6080:6080"  ## expose HTTP server
    links:
     - "selenium:selenium"